# Generated by Django 2.2.1 on 2019-05-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_text', models.CharField(max_length=2000)),
                ('chat_user', models.CharField(max_length=30)),
            ],
        ),
    ]
