# Generated by Django 2.2.1 on 2019-05-23 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ch', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Text',
            new_name='Textes',
        ),
    ]
